2025-04-07 19:52:58,826 INFO    StreamThr :1260966 [internal.py:wandb_internal():85] W&B internal server running at pid: 1260966, started at: 2025-04-07 19:52:58.817853
2025-04-07 19:52:58,828 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status
2025-04-07 19:52:58,847 INFO    WriterThread:1260966 [datastore.py:open_for_write():87] open: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/run-m7cc48xg.wandb
2025-04-07 19:52:58,856 DEBUG   SenderThread:1260966 [sender.py:send():379] send: header
2025-04-07 19:52:59,146 DEBUG   SenderThread:1260966 [sender.py:send():379] send: run
2025-04-07 19:52:59,640 INFO    SenderThread:1260966 [dir_watcher.py:__init__():211] watching files in: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files
2025-04-07 19:52:59,640 INFO    SenderThread:1260966 [sender.py:_start_run_threads():1188] run started: m7cc48xg with start time 1744048378.843048
2025-04-07 19:52:59,702 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: check_version
2025-04-07 19:52:59,703 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: check_version
2025-04-07 19:52:59,795 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: run_start
2025-04-07 19:53:00,806 DEBUG   HandlerThread:1260966 [system_info.py:__init__():26] System info init
2025-04-07 19:53:00,806 DEBUG   HandlerThread:1260966 [system_info.py:__init__():41] System info init done
2025-04-07 19:53:00,806 INFO    HandlerThread:1260966 [system_monitor.py:start():194] Starting system monitor
2025-04-07 19:53:00,806 INFO    SystemMonitor:1260966 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-07 19:53:00,807 INFO    HandlerThread:1260966 [system_monitor.py:probe():214] Collecting system info
2025-04-07 19:53:00,807 INFO    SystemMonitor:1260966 [interfaces.py:start():188] Started cpu monitoring
2025-04-07 19:53:00,809 INFO    SystemMonitor:1260966 [interfaces.py:start():188] Started disk monitoring
2025-04-07 19:53:00,810 INFO    SystemMonitor:1260966 [interfaces.py:start():188] Started gpu monitoring
2025-04-07 19:53:00,814 INFO    SystemMonitor:1260966 [interfaces.py:start():188] Started memory monitoring
2025-04-07 19:53:00,818 INFO    SystemMonitor:1260966 [interfaces.py:start():188] Started network monitoring
2025-04-07 19:53:00,878 DEBUG   HandlerThread:1260966 [system_info.py:probe():152] Probing system
2025-04-07 19:53:00,896 DEBUG   HandlerThread:1260966 [system_info.py:_probe_git():137] Probing git
2025-04-07 19:53:01,114 DEBUG   HandlerThread:1260966 [system_info.py:_probe_git():145] Probing git done
2025-04-07 19:53:01,114 DEBUG   HandlerThread:1260966 [system_info.py:probe():200] Probing system done
2025-04-07 19:53:01,114 DEBUG   HandlerThread:1260966 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-131-generic-x86_64-with-glibc2.35', 'python': '3.11.6', 'heartbeatAt': '2025-04-07T17:53:00.878432', 'startedAt': '2025-04-07T17:52:58.713290', 'docker': None, 'cuda': None, 'args': ('--dataset', 'UnconditionalSeismic3D', '--model_type', 'PreconditionedDenoiser3D', '--save_dir', 'GenCFD/outputs/UnconditionalSeismic3D-2', '--num_train_steps', '5000000', '--worker', '4', '--batch_size', '1'), 'state': 'running', 'program': '-m GenCFD.train.train_gencfd', 'codePathLocal': None, 'git': {'remote': 'https://github.com/LuisCarretero/GenCFD.git', 'commit': '7ff7fb7bbc95817b317583c33e6ab301b6e83491'}, 'email': 'luis.carretero@gmx.de', 'root': '/cluster/home/lcarretero/workspace/rds/GenCFD', 'host': 'eu-lo-g3-003', 'username': 'lcarretero', 'executable': '/cluster/home/lcarretero/python_envs/rds-misc/bin/python3', 'cpu_count': 128, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1545.7832890625, 'min': 1500.0, 'max': 2250.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3382.904, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3383.102, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3397.309, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}], 'disk': {'/': {'total': 10.0, 'used': 7.213817596435547}}, 'gpu': 'NVIDIA GeForce RTX 2080 Ti', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}], 'memory': {'total': 501.4531936645508}}
2025-04-07 19:53:01,114 INFO    HandlerThread:1260966 [system_monitor.py:probe():224] Finished collecting system info
2025-04-07 19:53:01,114 INFO    HandlerThread:1260966 [system_monitor.py:probe():227] Publishing system info
2025-04-07 19:53:01,129 INFO    HandlerThread:1260966 [system_monitor.py:probe():229] Finished publishing system info
2025-04-07 19:53:01,296 DEBUG   SenderThread:1260966 [sender.py:send():379] send: files
2025-04-07 19:53:01,296 INFO    SenderThread:1260966 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-04-07 19:53:01,594 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515d2905390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:53:01,594 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:53:01,594 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:53:01,654 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/wandb-metadata.json
2025-04-07 19:53:02,819 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515e07cc990>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:53:02,819 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:53:02,819 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:53:04,297 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:04,965 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515e07a9bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:53:04,966 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:53:04,966 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:53:04,966 INFO    wandb-upload_0:1260966 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1515e07a9bd0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515e07a9bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515e07a9bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2871, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-04-07 19:53:06,263 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: python_packages
2025-04-07 19:53:06,263 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: python_packages
2025-04-07 19:53:06,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:53:06,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:06,277 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:53:06,510 DEBUG   SenderThread:1260966 [sender.py:send():379] send: telemetry
2025-04-07 19:53:06,686 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/requirements.txt
2025-04-07 19:53:07,275 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:08,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:09,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:09,713 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/output.log
2025-04-07 19:53:09,830 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515d2905790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:53:09,831 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:53:09,831 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:53:09,902 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:10,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:11,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:11,726 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/output.log
2025-04-07 19:53:12,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:13,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:14,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:15,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:15,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:16,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:17,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:18,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:19,133 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515d29ceb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:53:19,133 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:53:19,133 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:53:19,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:20,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:20,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:21,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:53:21,264 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:53:21,307 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:22,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:23,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:24,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:25,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:25,454 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:26,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:27,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:28,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:29,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:30,271 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:31,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:31,271 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:31,864 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/config.yaml
2025-04-07 19:53:32,271 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:33,271 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:34,271 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:35,271 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:35,948 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515e0760490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:53:35,948 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:53:35,948 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:53:36,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:53:36,264 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:53:36,307 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:36,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:37,272 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:38,272 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:39,272 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:40,378 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:41,378 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:42,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:42,378 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:43,378 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:44,379 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:45,379 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:46,381 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:47,383 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:48,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:48,383 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:49,383 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:50,385 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:51,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:53:51,264 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:53:51,388 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:52,392 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:53,395 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:53,498 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:54,395 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:55,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:56,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:57,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:58,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:53:59,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:53:59,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:00,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:00,818 DEBUG   SystemMonitor:1260966 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-07 19:54:00,822 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:54:01,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:02,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:03,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:04,396 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:05,267 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:05,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:06,267 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:54:06,267 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:54:06,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:07,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:08,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:09,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:10,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:10,489 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:11,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:12,397 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:13,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:14,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:15,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:15,675 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515d0501d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:54:15,676 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:54:15,676 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:54:16,267 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:16,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:17,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:18,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:19,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:20,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:21,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:54:21,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:54:21,398 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:21,446 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:22,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:23,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:24,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:25,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:26,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:27,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:27,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:28,399 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:29,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:30,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:30,825 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:54:31,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:32,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:33,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:33,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:34,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:35,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:36,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:54:36,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:54:36,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:37,400 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:38,401 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:38,454 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:39,403 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:40,404 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:41,405 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:42,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:43,410 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:44,268 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:44,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:45,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:46,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:47,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:48,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:49,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:50,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:50,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:51,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:54:51,264 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:54:51,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:52,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:53,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:54,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:55,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:55,445 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:54:56,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:57,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:58,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:54:59,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:00,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:00,828 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:55:00,833 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:01,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:02,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:03,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:04,519 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:05,518 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:06,264 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:55:06,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:55:06,506 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:06,518 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:07,518 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:08,519 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:09,519 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:10,519 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:11,519 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:12,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:12,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:13,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:14,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:15,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:16,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:17,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:17,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:18,520 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:19,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:20,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:21,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:55:21,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:55:21,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:22,495 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:22,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:23,116 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515d0501450>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:55:23,116 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:55:23,116 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:55:23,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:24,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:25,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:26,521 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:27,522 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:28,269 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:28,522 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:29,522 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:30,522 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:30,831 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:55:31,522 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:32,541 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:33,541 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:34,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:34,541 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:35,541 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:36,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:55:36,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:55:36,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:37,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:38,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:39,455 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:39,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:40,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:41,542 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:42,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:43,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:44,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:45,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:45,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:46,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:47,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:48,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:49,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:50,270 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:50,543 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:51,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:55:51,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:55:51,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:52,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:53,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:54,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:55,463 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:55:55,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:56,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:57,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:55:58,544 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:00,380 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:00,834 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:56:00,838 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:01,380 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:02,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:03,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:04,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:05,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:06,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:56:06,265 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:56:06,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:06,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:07,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:07,989 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: partial_history
2025-04-07 19:56:07,990 DEBUG   SenderThread:1260966 [sender.py:send():379] send: history
2025-04-07 19:56:07,991 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: summary_record
2025-04-07 19:56:08,004 INFO    SenderThread:1260966 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-04-07 19:56:08,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:08,678 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/wandb-summary.json
2025-04-07 19:56:09,406 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:09,695 INFO    Thread-12 :1260966 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_195258-m7cc48xg/files/output.log
2025-04-07 19:56:10,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:11,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:12,273 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:12,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:13,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:14,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:15,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:16,407 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:17,273 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:17,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:18,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:19,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:20,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:21,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:56:21,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:56:21,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:22,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:22,458 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:23,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:24,408 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:25,409 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:26,411 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:27,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:28,274 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:28,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:29,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:30,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:30,836 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:56:31,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:32,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:33,274 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:33,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:34,412 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:35,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:36,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:56:36,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:56:36,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:37,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:38,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:38,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:39,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:40,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:41,413 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:42,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:43,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:44,275 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:44,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:45,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:46,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:47,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:48,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:49,414 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:50,275 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:50,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:51,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:56:51,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:56:51,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:52,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:53,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:54,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:55,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:55,532 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:56:56,415 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:57,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:58,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:56:59,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:00,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:00,843 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:57:00,848 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:01,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:02,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:03,416 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:04,417 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:05,417 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:06,265 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:57:06,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:57:06,418 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:06,515 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:07,418 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:08,418 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:09,418 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:10,418 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:11,418 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:12,275 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:12,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:13,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:14,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:15,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:16,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:17,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:18,275 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:18,419 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:19,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:20,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:21,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:57:21,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:57:21,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:22,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:23,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:23,510 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:24,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:25,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:26,420 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:27,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:28,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:29,275 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:29,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:30,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:30,842 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:57:31,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:32,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:33,421 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:34,276 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:34,422 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:35,422 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:36,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:57:36,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:57:36,422 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:37,422 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:38,422 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:39,422 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:39,516 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:40,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:41,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:42,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:43,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:44,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:45,276 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:45,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:46,423 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:47,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:48,524 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:49,524 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:50,276 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:50,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:51,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:57:51,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:57:51,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:51,533 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/m7cc48xg/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T175301Z&X-Goog-Expires=86399&X-Goog-Signature=702cf9a605a9b9d250fa835bebcadbe1ce57363c49b2dcafe19dee7acabeace322fa5228b914f1fa4e2ea96ea9530168417cec5386c0b4af6d65875ecbd8663d7c800c84bd28359c6c65ffef6e0fc47ba08a4b942736f3a7f1608b60d42f95faca5e9678e2b46bfb52296935aea11ae29189fcbbce25ec4029d23a0474322be489ec5b38e6d92786c96b48f4f00f74b1d8f4265d4e1a6580e5dddeac8940f4cd9890d234d1647d1e26999edd7c594f5c803bbe9db4ad198137e2f179804356a53f0f2a8d6a96fb5d902f7f4d768fb2394ca259b9b70591deb524b16467586113012542af26c0b714678ea61b28c46a238f92bb87dbc0f21a2a5702a5cb8d3ba2&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1515d0501f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 19:57:51,533 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15143'}
2025-04-07 19:57:51,533 ERROR   wandb-upload_0:1260966 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 19:57:52,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:53,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:54,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:55,467 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:57:55,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:56,525 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:57,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:58,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:57:59,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:00,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:00,845 DEBUG   SenderThread:1260966 [sender.py:send():379] send: stats
2025-04-07 19:58:00,850 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:58:01,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:02,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:03,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:04,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:05,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:06,266 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 19:58:06,266 DEBUG   SenderThread:1260966 [sender.py:send_request():406] send_request: stop_status
2025-04-07 19:58:06,507 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 19:58:06,526 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:07,527 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:08,527 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:09,527 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:10,527 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 19:58:11,527 DEBUG   HandlerThread:1260966 [handler.py:handle_request():158] handle_request: internal_messages
