2025-04-07 20:59:34,304 INFO    StreamThr :1332309 [internal.py:wandb_internal():85] W&B internal server running at pid: 1332309, started at: 2025-04-07 20:59:34.295822
2025-04-07 20:59:34,306 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status
2025-04-07 20:59:34,321 INFO    WriterThread:1332309 [datastore.py:open_for_write():87] open: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/run-bfcmw573.wandb
2025-04-07 20:59:34,331 DEBUG   SenderThread:1332309 [sender.py:send():379] send: header
2025-04-07 20:59:34,604 DEBUG   SenderThread:1332309 [sender.py:send():379] send: run
2025-04-07 20:59:35,076 INFO    SenderThread:1332309 [dir_watcher.py:__init__():211] watching files in: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files
2025-04-07 20:59:35,076 INFO    SenderThread:1332309 [sender.py:_start_run_threads():1188] run started: bfcmw573 with start time 1744052374.316064
2025-04-07 20:59:35,141 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: check_version
2025-04-07 20:59:35,142 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: check_version
2025-04-07 20:59:35,237 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: run_start
2025-04-07 20:59:36,017 DEBUG   HandlerThread:1332309 [system_info.py:__init__():26] System info init
2025-04-07 20:59:36,017 DEBUG   HandlerThread:1332309 [system_info.py:__init__():41] System info init done
2025-04-07 20:59:36,017 INFO    HandlerThread:1332309 [system_monitor.py:start():194] Starting system monitor
2025-04-07 20:59:36,018 INFO    SystemMonitor:1332309 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-07 20:59:36,018 INFO    HandlerThread:1332309 [system_monitor.py:probe():214] Collecting system info
2025-04-07 20:59:36,049 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started cpu monitoring
2025-04-07 20:59:36,054 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started disk monitoring
2025-04-07 20:59:36,054 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started gpu monitoring
2025-04-07 20:59:36,058 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started memory monitoring
2025-04-07 20:59:36,059 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started network monitoring
2025-04-07 20:59:36,087 DEBUG   HandlerThread:1332309 [system_info.py:probe():152] Probing system
2025-04-07 20:59:36,124 DEBUG   HandlerThread:1332309 [system_info.py:_probe_git():137] Probing git
2025-04-07 20:59:36,308 DEBUG   HandlerThread:1332309 [system_info.py:_probe_git():145] Probing git done
2025-04-07 20:59:36,308 DEBUG   HandlerThread:1332309 [system_info.py:probe():200] Probing system done
2025-04-07 20:59:36,308 DEBUG   HandlerThread:1332309 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-131-generic-x86_64-with-glibc2.35', 'python': '3.11.6', 'heartbeatAt': '2025-04-07T18:59:36.087922', 'startedAt': '2025-04-07T18:59:34.178449', 'docker': None, 'cuda': None, 'args': ('--dataset', 'UnconditionalSeismic3D', '--model_type', 'PreconditionedDenoiser3D', '--save_dir', 'GenCFD/outputs/UnconditionalSeismic3D-2', '--num_train_steps', '5000000', '--worker', '4', '--batch_size', '8', '--track_memory'), 'state': 'running', 'program': '-m GenCFD.train.train_gencfd', 'codePathLocal': None, 'git': {'remote': 'https://github.com/LuisCarretero/GenCFD.git', 'commit': '7ff7fb7bbc95817b317583c33e6ab301b6e83491'}, 'email': 'luis.carretero@gmx.de', 'root': '/cluster/home/lcarretero/workspace/rds/GenCFD', 'host': 'eu-lo-g3-014', 'username': 'lcarretero', 'executable': '/cluster/home/lcarretero/python_envs/rds-misc/bin/python3', 'cpu_count': 128, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1960.3931093750002, 'min': 1500.0, 'max': 2250.0}, 'cpu_freq_per_core': [{'current': 1685.351, 'min': 1500.0, 'max': 2250.0}, {'current': 3397.317, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.688, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3395.89, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.927, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.302, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.995, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.742, 'min': 1500.0, 'max': 2250.0}, {'current': 3389.746, 'min': 1500.0, 'max': 2250.0}, {'current': 2743.334, 'min': 1500.0, 'max': 2250.0}, {'current': 3389.554, 'min': 1500.0, 'max': 2250.0}, {'current': 2672.858, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.354, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.463, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.455, 'min': 1500.0, 'max': 2250.0}, {'current': 2632.261, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.655, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.509, 'min': 1500.0, 'max': 2250.0}, {'current': 3389.454, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.598, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.188, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.512, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.576, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.499, 'min': 1500.0, 'max': 2250.0}, {'current': 2731.821, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.739, 'min': 1500.0, 'max': 2250.0}, {'current': 3284.296, 'min': 1500.0, 'max': 2250.0}, {'current': 3391.14, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3391.182, 'min': 1500.0, 'max': 2250.0}, {'current': 2741.638, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.046, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.123, 'min': 1500.0, 'max': 2250.0}, {'current': 3387.831, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}], 'disk': {'/': {'total': 10.0, 'used': 7.213996887207031}}, 'gpu': 'NVIDIA GeForce RTX 2080 Ti', 'gpu_count': 4, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}], 'memory': {'total': 501.45680236816406}}
2025-04-07 20:59:36,309 INFO    HandlerThread:1332309 [system_monitor.py:probe():224] Finished collecting system info
2025-04-07 20:59:36,309 INFO    HandlerThread:1332309 [system_monitor.py:probe():227] Publishing system info
2025-04-07 20:59:36,328 INFO    HandlerThread:1332309 [system_monitor.py:probe():229] Finished publishing system info
2025-04-07 20:59:36,416 DEBUG   SenderThread:1332309 [sender.py:send():379] send: files
2025-04-07 20:59:36,416 INFO    SenderThread:1332309 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-04-07 20:59:36,705 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c55690>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:36,705 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:36,705 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:37,091 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/wandb-metadata.json
2025-04-07 20:59:37,936 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c09ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:37,936 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:37,936 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:39,417 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:40,309 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:40,309 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:40,309 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:40,309 INFO    wandb-upload_0:1332309 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2871, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-04-07 20:59:41,022 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: python_packages
2025-04-07 20:59:41,022 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: python_packages
2025-04-07 20:59:41,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 20:59:41,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:41,036 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 20:59:41,119 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/requirements.txt
2025-04-07 20:59:41,280 DEBUG   SenderThread:1332309 [sender.py:send():379] send: telemetry
2025-04-07 20:59:42,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:43,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:44,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:44,137 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/output.log
2025-04-07 20:59:45,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:45,127 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:45,169 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53d8bd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:45,169 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:45,169 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:46,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:46,150 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/output.log
2025-04-07 20:59:47,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:48,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:49,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:50,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:51,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:51,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:52,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:53,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:53,457 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53dbe310>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:53,457 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:53,457 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:54,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:55,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:56,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 20:59:56,023 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 20:59:56,065 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:56,251 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:57,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:58,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:59,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:00,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:01,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:02,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:02,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:03,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:04,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:05,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:06,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:07,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:08,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:08,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:09,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:10,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:10,307 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53d8ad50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:00:10,307 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:00:10,307 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:00:11,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:11,023 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:11,069 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:11,314 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/config.yaml
2025-04-07 21:00:12,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:13,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:14,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:15,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:16,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:16,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:17,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:18,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:19,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:20,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:21,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:21,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:22,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:23,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:24,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:25,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:26,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:26,023 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:26,065 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:26,274 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:27,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:28,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:29,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:30,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:31,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:32,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:32,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:33,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:34,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:35,033 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:36,033 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:36,059 DEBUG   SystemMonitor:1332309 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-07 21:00:36,063 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:00:37,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:37,065 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:38,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:39,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:40,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:41,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:41,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:41,069 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:42,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:42,302 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:43,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:43,283 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c33750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:00:43,283 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:00:43,283 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:00:44,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:45,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:46,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:47,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:48,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:48,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:49,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:50,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:51,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:52,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:53,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:54,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:54,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:55,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:56,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:56,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:56,069 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:57,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:58,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:59,234 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:59,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:00,234 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:01,234 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:02,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:03,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:04,236 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:05,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:05,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:06,067 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:01:06,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:07,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:08,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:09,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:10,070 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:10,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:11,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:11,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:11,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:12,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:13,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:14,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:15,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:15,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:16,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:17,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:18,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:19,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:20,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:21,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:21,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:22,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:23,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:24,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:25,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:26,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:26,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:26,236 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:26,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:27,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:28,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:29,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:30,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:31,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:32,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:32,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:33,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:34,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:35,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:36,070 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:01:36,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:37,073 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:37,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:38,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:39,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:40,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:41,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:41,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:41,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:42,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:42,294 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:43,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:44,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:45,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:46,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:47,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:48,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:48,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:49,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:50,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:51,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:52,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:53,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:53,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:54,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:55,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:56,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:56,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:56,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:56,393 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53dbf1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:01:56,393 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:01:56,393 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:01:57,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:58,224 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:58,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:59,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:00,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:01,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:02,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:03,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:04,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:04,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:05,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:06,074 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:02:06,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:07,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:08,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:09,076 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:09,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:10,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:11,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:11,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:11,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:12,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:13,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:14,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:14,262 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:15,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:16,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:17,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:18,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:19,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:20,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:20,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:21,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:22,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:23,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:24,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:25,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:25,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:26,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:26,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:26,422 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:27,421 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:28,422 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:29,421 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:30,271 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:30,421 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:31,425 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:32,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:33,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:34,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:35,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:36,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:36,076 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:02:36,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:37,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:38,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:39,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:40,428 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:41,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:41,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:41,274 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:41,428 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:42,428 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:43,429 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:44,429 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:45,429 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:46,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:47,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:47,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:48,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:49,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:50,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:51,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:52,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:53,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:53,431 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:54,431 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:55,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:56,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:56,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:56,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:57,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:58,210 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:58,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:59,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:00,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:01,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:02,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:03,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:04,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:04,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:05,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:06,080 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:03:06,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:07,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:08,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
